"""Public API for :mod:`jainsons_llm_router`."""

from .adapters import (
    AdapterFailure,
    AnthropicAdapter,
    FakeAdapter,
    GeminiAdapter,
    GenericHTTPAdapter,
    MistralAdapter,
    NullAdapter,
    OpenRouterAdapter,
    PriceCard,
    ProviderAdapter,
)
from .errors import (
    BudgetDenied,
    ConfigurationError,
    ExactModelUnavailable,
    InvalidRequest,
    LedgerUnavailable,
    OutcomeUnknown,
    PaidNotApproved,
    ProviderFailure,
    RouteUnavailable,
    RouterError,
)
from .ledger import (
    FileLedger,
    IdempotencyConflict,
    LedgerReservation,
    ReservationSpec,
    UsageLedger,
    hash_private_identifier,
)
from .models import (
    AdapterRequest,
    AdapterResult,
    AttemptSummary,
    BillingClass,
    BudgetCap,
    BudgetRemaining,
    CallerContext,
    Candidate,
    CandidateHealth,
    ChargeEstimate,
    ExactModel,
    FailurePhase,
    LLMRequest,
    LLMResult,
    PaidApproval,
    RoutePolicy,
    RouteSelection,
    RouterConfig,
    RouterHealth,
    Usage,
    UseRoute,
)
from .observability import (
    EventLogger,
    InMemoryEventLogger,
    NullEventLogger,
    StructuredEventLogger,
)
from .router import Clock, Router, SystemClock, create_router

__all__ = [
    "AdapterFailure",
    "AdapterRequest",
    "AdapterResult",
    "AnthropicAdapter",
    "AttemptSummary",
    "BillingClass",
    "BudgetCap",
    "BudgetDenied",
    "BudgetRemaining",
    "CallerContext",
    "Candidate",
    "CandidateHealth",
    "ChargeEstimate",
    "Clock",
    "ConfigurationError",
    "EventLogger",
    "ExactModel",
    "ExactModelUnavailable",
    "FailurePhase",
    "FakeAdapter",
    "FileLedger",
    "GeminiAdapter",
    "GenericHTTPAdapter",
    "IdempotencyConflict",
    "InMemoryEventLogger",
    "InvalidRequest",
    "LLMRequest",
    "LLMResult",
    "LedgerReservation",
    "LedgerUnavailable",
    "MistralAdapter",
    "NullAdapter",
    "NullEventLogger",
    "OpenRouterAdapter",
    "OutcomeUnknown",
    "PaidApproval",
    "PaidNotApproved",
    "PriceCard",
    "ProviderAdapter",
    "ProviderFailure",
    "ReservationSpec",
    "RoutePolicy",
    "RouteSelection",
    "RouteUnavailable",
    "Router",
    "RouterConfig",
    "RouterError",
    "RouterHealth",
    "StructuredEventLogger",
    "SystemClock",
    "Usage",
    "UsageLedger",
    "UseRoute",
    "create_router",
    "hash_private_identifier",
]

__version__ = "0.2.0"
